# Generated by Django 4.2.29 on 2026-03-12 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActualizacionDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('prototipos_evaluados', models.PositiveIntegerField(default=0)),
                ('cambios_detectados', models.PositiveIntegerField(default=0)),
                ('cambios_verificados', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Actualización de Dashboard',
                'verbose_name_plural': 'Actualizaciones de Dashboard',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('año_inicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('año_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('enlace_wiki_proyecto', models.URLField(blank=True, max_length=500)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='diagnostico.actividad')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('url_wiki', models.URLField(blank=True, max_length=500)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototipos', to='diagnostico.proyecto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('subseccion', models.CharField(max_length=100)),
                ('status_scraper', models.CharField(choices=[('Completa', 'Completa'), ('Vacía', 'Vacía'), ('Incompleta', 'Incompleta')], max_length=20)),
                ('contenido_chars', models.PositiveIntegerField(default=0)),
                ('fecha_scraper', models.DateTimeField()),
                ('verificado', models.BooleanField(default=False)),
                ('status_override', models.CharField(blank=True, choices=[('Completa', 'Completa'), ('Vacía', 'Vacía'), ('Incompleta', 'Incompleta')], help_text='Dejar vacío para aceptar lo que detectó el scraper', max_length=20)),
                ('notas_mejora', models.TextField(blank=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('status_final_cache', models.CharField(blank=True, choices=[('Completa', 'Completa'), ('Vacía', 'Vacía'), ('Incompleta', 'Incompleta')], max_length=20)),
                ('prototipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='diagnostico.prototipo')),
            ],
            options={
                'verbose_name': 'Evaluación Wiki',
                'verbose_name_plural': 'Evaluaciones Wiki',
                'ordering': ['seccion', 'subseccion'],
                'unique_together': {('prototipo', 'seccion', 'subseccion')},
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDocSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('nombre_proyecto', 'Nombre de proyecto'), ('descripcion_proyecto', 'Descripción de proyecto'), ('trazas_proceso', 'Trazas del proceso de prototipado'), ('prototipo_partes', 'El prototipo y/o partes de él'), ('fotos_prototipo', 'Fotografías del prototipo'), ('fotos_personas', 'Fotografías de las personas colaboradoras'), ('qr_enlace_wiki', 'QR o enlace a la wiki')], max_length=50)),
                ('status', models.CharField(choices=[('Completa', 'Completa'), ('Incompleta', 'Incompleta')], max_length=20)),
                ('notas_mejora', models.TextField(blank=True)),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluado_por', models.CharField(blank=True, max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docspaces', to='diagnostico.proyecto')),
            ],
            options={
                'verbose_name': 'Evaluación DocSpace',
                'verbose_name_plural': 'Evaluaciones DocSpace',
                'ordering': ['seccion'],
                'unique_together': {('proyecto', 'seccion')},
            },
        ),
    ]
