# Generated by Django 6.0.3 on 2026-04-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondocspace',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionwiki',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
